INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (0, 0, 'Adam');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (1, 0, 'Ben');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (2, 0, 'Carla');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (3, 0, 'David');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (4, 0, 'Eunice');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (5, 0, 'Frank');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (6, 0, 'Getrude');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (7, 0, 'Harry');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (8, 0, 'Isaac');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (9, 0, 'Julia');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (10, 0, 'Kevin');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (11, 0, 'Laura');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (12, 0, 'Matthew');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (13, 0, 'Nico');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (14, 0, 'Oscar');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (15, 0, 'Penny');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (16, 0, 'Queen');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (17, 0, 'Roger');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (18, 0, 'Sam');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (19, 0, 'Tara');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TYPE_NAME,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (0, 'WAGER', 100, 0, '2022-04-22 10:34:23');