INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (0, 0, 'Adam');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (1, 0, 'Ben');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (2, 0, 'Carla');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (3, 0, 'David');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (4, 0, 'Eunice');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (5, 0, 'Frank');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (6, 0, 'Getrude');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (7, 0, 'Harry');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (8, 0, 'Isaac');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (9, 0, 'Julia');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (10, 0, 'Kevin');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (11, 0, 'Laura');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (12, 0, 'Matthew');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (13, 0, 'Nico');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (14, 0, 'Oscar');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (15, 0, 'Penny');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (16, 0, 'Queen');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (17, 0, 'Roger');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (18, 0, 'Sam');
INSERT INTO PLAYER (PLAYER_ID, BALANCE, USERNAME)
VALUES (19, 0, 'Tara');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (0, 'WAGER', 100, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (1, 'WIN', 2000, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (2, 'WAGER', 700, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (3, 'WAGER', 900, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (4, 'WIN', 32, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (5, 'WIN', 878, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (6, 'WAGER', 150, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (7, 'WAGER', 10000, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (8, 'WIN', 107, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (9, 'WAGER', 7, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (10, 'WAGER', 555, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (11, 'WAGER', 907, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (12, 'WIN', 366, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (13, 'WIN', 987, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (14, 'WIN', 400, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (15, 'WAGER', 2075, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (16, 'WIN', 2075, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (17, 'WAGER', 800, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (18, 'WAGER', 1000, 0, '2022-04-22 10:34:23');
INSERT INTO TRANSACTION (
        TRANSACTION_ID,
        TRANSACTION_TYPE,
        AMOUNT,
        PLAYER_ID,
        DATE_TIME
    )
VALUES (19, 'WIN', 1117, 0, '2022-04-22 10:34:23');